version: "3"
services:
  app:
    build: .
    image: otelapp
    ports:
      - "5001:80"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: "--config=/etc/otel-collector.yaml"
    ports:
      - "4317:4317"
      - "8889:8889"
    volumes:
      - ./grafana/otel-collector.yaml:/etc/otel-collector.yaml

  tempo:
    image: grafana/tempo:latest
    command: "-config.file=/etc/tempo.yaml"
    volumes:
      - ./grafana/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200"   # tempo
      - "4317"   # otlp grpc

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./grafana/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:latest
    command: "-config.file=/etc/loki/local-config.yaml"
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:9.3.2
    volumes:
      - ./grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"
